### ISSUE TITLE
Null-safe operator followed by a property named `class` results in a syntax error

### ISSUE THREAD

**Issue by shufo** [glayzzle/php-parser#1003]
## Context
- php-parser 3.1.0
- https://github.com/shufo/vscode-blade-formatter/issues/544
  - I noticed this issue when my extension user reports the syntax check issue
 
## Problem

When property named `class` is exists after null safe operator, it will throws an exception.

```js
const target = `
  $record->learner->currentEnrollment?->class->grade->code
`;
// Retrieve the AST from the specified source
const eval = parser.parseEval(target);


// then it will throws an exception
/home/shuhei/develop/php-parser/src/parser.js:357
    throw err;
    ^

SyntaxError: Parse Error : syntax error, unexpected 'class' (T_CLASS) on line 2
    at Parser.raiseError (/home/shuhei/develop/php-parser/src/parser.js:349:17)
    at Parser.error (/home/shuhei/develop/php-parser/src/parser.js:397:15)
    at Parser.read_what (/home/shuhei/develop/php-parser/src/parser/variable.js:161:14)
    at Parser.recursive_variable_chain_scan (/home/shuhei/develop/php-parser/src/parser/variable.js:235:38)
    at Parser.read_variable (/home/shuhei/develop/php-parser/src/parser/variable.js:85:17)
    at Parser.read_expr_item (/home/shuhei/develop/php-parser/src/parser/expr.js:455:19)
    at Parser.read_expr (/home/shuhei/develop/php-parser/src/parser/expr.js:18:19)
    at Parser.read_statement (/home/shuhei/develop/php-parser/src/parser/statement.js:416:27)
    at Parser.read_top_statement (/home/shuhei/develop/php-parser/src/parser/statement.js:77:21)
    at Parser.read_start (/home/shuhei/develop/php-parser/src/parser/main.js:18:19) {
  lineNumber: 2,
  fileName: 'eval',
  columnNumber: 40
}
```

Maybe it is recognized as reserved word.

It only happens when you put `class` property after null safe operator.
So `class` property with normal property access is ok.

```php
// This works
$record->learner->currentEnrollment->class->grade?->code;
```

When I check syntax on php directly, it's ok. 

```php
$  php -v
PHP 8.1.2 (cli) (built: Aug 15 2022 12:24:10) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

$ vim test.php
```

```php
<?php
echo $record->learner->currentEnrollment?->class->grade->code;
```

```bash
$  php --syntax-check test.php
No syntax errors detected in test.php
```

Sorry for no PR, I tried fix this but I don't know the right solution.

**Comment by Sxxov** [comment]
This seems to be an issue with other keywords too, like `echo`:

<details>
  <summary>Stacktrace</summary>
  
 ```
Parse Error : syntax error, unexpected 'echo' (T_ECHO) on line 29
  27 | ])
  28 | 	->ifErr()
> 29 | 	?->echo();
     | 	  ^
  30 |
SyntaxError: Parse Error : syntax error, unexpected 'echo' (T_ECHO) on line 29
  27 | ])
  28 | 	->ifErr()
> 29 | 	?->echo();
     | 	  ^
  30 |
    at Parser.raiseError (c:\xampp\htdocs\node_modules\php-parser\src\parser.js:349:17)
    at Parser.error (c:\xampp\htdocs\node_modules\php-parser\src\parser.js:397:15)
    at Parser.read_what (c:\xampp\htdocs\node_modules\php-parser\src\parser\variable.js:161:14)
    at Parser.recursive_variable_chain_scan (c:\xampp\htdocs\node_modules\php-parser\src\parser\variable.js:235:38)
    at Parser.read_variable (c:\xampp\htdocs\node_modules\php-parser\src\parser\variable.js:85:17)
    at Parser.read_expr_item (c:\xampp\htdocs\node_modules\php-parser\src\parser\expr.js:455:19)
    at Parser.read_expr (c:\xampp\htdocs\node_modules\php-parser\src\parser\expr.js:18:19)
    at Parser.read_statement (c:\xampp\htdocs\node_modules\php-parser\src\parser\statement.js:396:34)
    at Parser.read_top_statement (c:\xampp\htdocs\node_modules\php-parser\src\parser\statement.js:78:21)
    at Parser.read_top_statements (c:\xampp\htdocs\node_modules\php-parser\src\parser\statement.js:18:30)
    at Parser.read_namespace (c:\xampp\htdocs\node_modules\php-parser\src\parser\namespace.js:37:26)
    at Parser.read_start (c:\xampp\htdocs\node_modules\php-parser\src\parser\main.js:16:19)
    at Parser.parse (c:\xampp\htdocs\node_modules\php-parser\src\parser.js:301:22)
    at Engine.parseCode (c:\xampp\htdocs\node_modules\php-parser\src\index.js:187:22)
 ```
</details>
