### ISSUE TITLE
Attribute parsing with string concatenation

### ISSUE THREAD

**Issue by NorthBlue333** [glayzzle/php-parser#1076]
Hello,
The following syntax is correct but I get:
```
Error: Bad terminal sequence "." at line 30 (offset 995)
     at Lexer.matchST_ATTRIBUTE (/srv/app/node_modules/php-parser/src/lexer/attribute.js:80:11)
     at Lexer.next (/srv/app/node_modules/php-parser/src/lexer.js:511:26)
     at Lexer.lex (/srv/app/node_modules/php-parser/src/lexer.js:413:20)
     at Lexer.lex (/srv/app/node_modules/php-parser/src/lexer.js:413:35)
     at Parser.lex (/srv/app/node_modules/php-parser/src/parser.js:702:29)
     at Parser.next (/srv/app/node_modules/php-parser/src/parser.js:611:8)
     at Parser.read_array (/srv/app/node_modules/php-parser/src/parser/array.js:29:14)
     at Parser.read_dereferencable_scalar (/srv/app/node_modules/php-parser/src/parser/scalar.js:193:23)
     at Parser.read_scalar (/srv/app/node_modules/php-parser/src/parser/scalar.js:284:23)
     at Parser.read_expr_item (/srv/app/node_modules/php-parser/src/parser/expr.js:540:19)
```

```php
#[ApiFilter(
            SearchFilter::class,
            strategy: 'i' . SearchFilter::STRATEGY_PARTIAL
        ) ]
```

It seems to be fixed by adding a `.` to the switch case of `lexer/attribute.js`, line 46.

**Comment by NorthBlue333** [comment]
Just did one!
