### ISSUE TITLE
Fails to parse classes with typed constants

### ISSUE THREAD

**Issue by davidrans** [glayzzle/php-parser#1133]
It looks like files that have typed constants are not parseable by the latest version (3.1.5).

Input file:
```
<?php

class Test {
   private const int MY_CONST = 3;
}
```
Error:
```
SyntaxError: Parse Error : syntax error, unexpected 'MY_CONST' (T_STRING), expecting '=' on line 4
    at Parser.raiseError (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser.js:349:17)
    at Parser.error (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser.js:397:15)
    at Parser.expect (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser.js:577:10)
    at Parser.read_constant_declaration (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser/class.js:261:18)
    at Parser.read_list (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser/utils.js:76:33)
    at Parser.read_constant_list (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser/class.js:237:24)
    at Parser.read_class_body (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser/class.js:117:32)
    at Parser.read_class_declaration_statement (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser/class.js:32:30)
    at Parser.read_top_statement (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser/statement.js:52:21)
    at Parser.read_start (/home/user/Code/node_modules/.pnpm/php-parser@3.1.5/node_modules/php-parser/src/parser/main.js:18:19) {
  lineNumber: 4,
  fileName: 'eval',
  columnNumber: 21
}
```

**Comment by Kenneth-Sills** [comment]
At a glance, [this](https://github.com/glayzzle/php-parser/blob/80eb9460679188f76166dd25a9a2666b8ff129aa/src/parser/class.js#L152) conditional needs to be updated to support type hint tokens proceeded by a constant list, then [`read_constant_declaration`](https://github.com/glayzzle/php-parser/blob/80eb9460679188f76166dd25a9a2666b8ff129aa/src/parser/class.js#L246) needs to be updated to use [read_optional_type](https://github.com/glayzzle/php-parser/blob/80eb9460679188f76166dd25a9a2666b8ff129aa/src/parser/class.js#L335).[^1] Finally, we'll need to throw that information into the [ClassConstant constructor](https://github.com/glayzzle/php-parser/blob/80eb9460679188f76166dd25a9a2666b8ff129aa/src/ast/classconstant.js).

Traits, interfaces, and enums go through this path, so should be supported implicitly. So as long as there's no complications, that should be all that's necessary.

@czosel Are y'all accepting PRs?

[^1]: I'm not too familiar with this library and what it would consider a parser error vs runtime error, but it's worth noting that there are [limitations on allowed types](https://wiki.php.net/rfc/typed_class_constants#supported_types).

**Comment by cseufert** [comment]
PR would be great

**Comment by genintho** [comment]
The code merged is not working if the class constant does not contain a type.

Example `'class Foo { public const CONSTANT = "Hello world!"; }'`

> classconstant › type hinted (supported)
> SyntaxError: Parse Error : syntax error, unexpected '=' on line 1
  347 |   message += " on line " + this.lexer.yylloc.first_line;
      348 |   if (!this.suppressErrors) {
    > 349 |     const err = new SyntaxError(
          |                 ^
      350 |       message,
      351 |       this.filename,
      352 |       this.lexer.yylloc.first_line,

      at Parser.Object.<anonymous>.Parser.raiseError (src/parser.js:349:17)
      at Parser.raiseError [as error] (src/parser.js:397:15)
      at Parser.error [as expect] (src/parser.js:577:10)



Working on a fix

**Comment by genintho** [comment]
PR opened

**Comment by Kenneth-Sills** [comment]
Thank you, @genintho! Apologies for not adding more test cases; 100% should have caught this. Let me know if you need any help with the fixes!

**Comment by genintho** [comment]
@Kenneth-Sills No worries, I think this PR fixes it. https://github.com/glayzzle/php-parser/pull/1147
