### ISSUE TITLE
Declare inside if

### ISSUE THREAD

**Issue by czosel** [glayzzle/php-parser#151]
Input:
```php
if ($var) {
    declare(ticks=1);
}
```
Output:
```
[error]     SyntaxError: Parse Error : syntax error, unexpected '}' on line 4
[error]     at parser.raiseError (/export/node_modules/php-parser/src/parser.js:290:17)
[error]     at parser.error (/export/node_modules/php-parser/src/parser.js:335:15)
[error]     at parser.read_expr_item (/export/node_modules/php-parser/src/parser/expr.js:420:12)
[error]     at parser.read_expr (/export/node_modules/php-parser/src/parser/expr.js:11:23)
[error]     at parser.read_statement (/export/node_modules/php-parser/src/parser/statement.js:386:21)
[error]     at parser.read_top_statement (/export/node_modules/php-parser/src/parser/statement.js:74:21)
[error]     at parser.read_statement (/export/node_modules/php-parser/src/parser/statement.js:339:28)
[error]     at parser.read_inner_statement (/export/node_modules/php-parser/src/parser/statement.js:186:21)
[error]     at parser.read_inner_statements (/export/node_modules/php-parser/src/parser/statement.js:86:30)
[error]     at parser.read_code_block (/export/node_modules/php-parser/src/parser/statement.js:401:14)
```

While we didn't really find information if this is actually allowed, PHP doesn't seem to complain:

```
php -a
Interactive mode enabled

php > if (true) {declare(ticks=1);}
php > if (false) {declare(ticks=1);}
php >
```

https://github.com/prettier/plugin-php/issues/392

**Comment by ichiriac** [comment]
**BREAKING CHANGE from V2**
---
Before declare statements where handled as namespace statements, so the statement automatically includes following nodes as body.

PHP may handle these statements at runtime so in order to parse them into statements, the node no longer includes automatically following nodes.
