### ISSUE TITLE
Parse php 7 & make the build to pass

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#16]
Error: Parse Error : unexpected ':', expecting '{' at line 167
    at Object.api.error (/home/travis/build/glayzzle/php-parser/src/parser.js:218:15)
    at Object.api.expect (/home/travis/build/glayzzle/php-parser/src/parser.js:322:16)
    at Object.read_function (/home/travis/build/glayzzle/php-parser/src/parser/function.js:44:16)
    at Object.read_class_body (/home/travis/build/glayzzle/php-parser/src/parser/class.js:121:29)
    at Object.read_class (/home/travis/build/glayzzle/php-parser/src/parser/class.js:39:34)
    at Object.read_top_statement (/home/travis/build/glayzzle/php-parser/src/parser/statement.js:48:23)
    at Object.read_start (/home/travis/build/glayzzle/php-parser/src/parser/main.js:18:21)
    at Object.api.parse (/home/travis/build/glayzzle/php-parser/src/parser.js:188:31)
    at Object.engine.parseCode (/home/travis/build/glayzzle/php-parser/main.js:77:19)
    at Object.module.exports.run (/home/travis/build/glayzzle/php-parser/bin/formats/php.js:19:20)
Error on test/token/symfony/src/Symfony/Bridge/ProxyManager/Tests/LazyProxy/Fixtures/php/lazy_service_with_hints.php
[Error: Parse Error : unexpected ':', expecting '{' at line 167]

--------------------------------------------------------------------------

FAIL : Expected "
" contents, but found "
EOF;
        if ("
FAIL : Token arrays have not the same length !
Error at : test/token/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
JS Tokens [ [ 'T_ENCAPSED_AND_WHITESPACE', '\nEOF;\n\n        if (', 820 ] ]
PHP Tokens [ [ 'T_ENCAPSED_AND_WHITESPACE', '\n', 820 ] ]
Error: Test "test/token/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php" does not pass !
    at test (/home/travis/build/glayzzle/php-parser/bin/test.js:153:19)
    at Object.<anonymous> (/home/travis/build/glayzzle/php-parser/bin/test.js:268:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Error on test/token/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
[Error: Test "test/token/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php" does not pass !]

--------------------------------------------------------------------------

Error: Parse Error : unexpected ':', expecting '{' at line 19
    at Object.api.error (/home/travis/build/glayzzle/php-parser/src/parser.js:218:15)
    at Object.api.expect (/home/travis/build/glayzzle/php-parser/src/parser.js:322:16)
    at Object.read_function (/home/travis/build/glayzzle/php-parser/src/parser/function.js:44:16)
    at Object.read_class_body (/home/travis/build/glayzzle/php-parser/src/parser/class.js:121:29)
    at Object.read_class (/home/travis/build/glayzzle/php-parser/src/parser/class.js:39:34)
    at Object.read_top_statement (/home/travis/build/glayzzle/php-parser/src/parser/statement.js:48:23)
    at Object.read_top_statements (/home/travis/build/glayzzle/php-parser/src/parser/statement.js:17:26)
    at Object.read_namespace (/home/travis/build/glayzzle/php-parser/src/parser/namespace.js:31:34)
    at Object.read_start (/home/travis/build/glayzzle/php-parser/src/parser/main.js:16:21)
    at Object.api.parse (/home/travis/build/glayzzle/php-parser/src/parser.js:188:31)
Error on test/token/symfony/src/Symfony/Component/PropertyInfo/Tests/Fixtures/Php7Dummy.php
[Error: Parse Error : unexpected ':', expecting '{' at line 19]

--------------------------------------------------------------------------

PHP Parse error:  syntax error, unexpected 'parseError' (T_STRING), expecting function (T_FUNCTION) in test/token/zf2/tests/ZendTest/Loader/_files/ParseError.php on line 15

**Comment by ichiriac** [comment]
everything passes, the last one is a real parse error
