### ISSUE TITLE
3.0.0-prerelease.2 and 3.0.0-prerelease.3 broken

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#178]
Error output:
```
 TypeError: Cannot set property 'prototype' of undefined
      
      at Function.Object.<anonymous>.Node.extends (node_modules/php-parser/src/ast/node.js:54:25)
      at Object.<anonymous> (node_modules/php-parser/src/ast/bin.js:18:30)
      at Object.<anonymous> (node_modules/php-parser/src/ast.js:301:3)
      at Object.<anonymous> (node_modules/php-parser/src/index.js:11:13)
      at Object.<anonymous> (src/parser.js:2:16)
      at Object.<anonymous> (src/index.js:3:15)
      at Object.<anonymous> (tests_config/run_spec.js:6:16)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:126:13)
      at process.emit (events.js:214:7)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

`3.0.0-prerelease.1` works good

**Comment by ichiriac** [comment]
can you try with `3.0.0-prerelease.4` seems that was an error on packaging, not sure to understand how ...

**Comment by evilebottnawi** [comment]
@ichiriac problem still exists :confused: Investigate

**Comment by evilebottnawi** [comment]
@ichiriac fixed, problem will be in `yarn`
