### ISSUE TITLE
[bug] multipleline string in parameter

### ISSUE THREAD

**Issue by evilebottnawi** [glayzzle/php-parser#203]
Input:
```php
function ($arg = 'string
string
string') {
    return $arg;
};
```

Output:
```shell
SyntaxError: Parse Error : syntax error, unexpected '(', expecting T_STRING on line 98
at parser.Object.<anonymous>.parser.raiseError (node_modules/php-parser/src/parser.js:300:17)
      at parser.Object.<anonymous>.parser.error (node_modules/php-parser/src/parser.js:345:15)
      at parser.Object.<anonymous>.parser.expect (node_modules/php-parser/src/parser.js:438:10)
      at parser.read_function_declaration (node_modules/php-parser/src/parser/function.js:94:18)
      at parser.read_function (node_modules/php-parser/src/parser/function.js:36:25)
      at parser.read_top_statement (node_modules/php-parser/src/parser/statement.js:42:21)
      at parser.read_start (node_modules/php-parser/src/parser/main.js:18:19)
      at parser.Object.<anonymous>.parser.parse [as parse] (node_modules/php-parser/src/parser.js:276:23)
      at engine.Object.<anonymous>.engine.parseCode (node_modules/php-parser/src/index.js:167:22)
      at Object.parseCode [as parse] (src/parser.js:27:61)
```

**Comment by ichiriac** [comment]
related to https://github.com/glayzzle/php-parser/issues/180 - missing the function name

**Comment by evilebottnawi** [comment]
@ichiriac oh yes, duplicate, my mistake
