### ISSUE TITLE
error parsing opencart

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#27]
See https://github.com/HvyIndustries/crane/issues/178#issuecomment-264452680 - Open Cart is not parsed correctly.

From Travis :

```
FAIL : Expected T_WHITESPACE token, but found T_INLINE_HTML
Error at : test/token/opencart/upload/catalog/model/extension/shipping/sf_express.php
JS Tokens [ [ 'T_INLINE_HTML', '\n', 273 ] ]
PHP Tokens [ [ 'T_WHITESPACE', '\n', 273 ] ]
Error: Test "test/token/opencart/upload/catalog/model/extension/shipping/sf_express.php" does not pass !
    at test (/home/travis/build/glayzzle/php-parser/bin/test.js:174:19)
    at runTests (/home/travis/build/glayzzle/php-parser/bin/test.js:319:9)
    at /home/travis/build/glayzzle/php-parser/bin/test.js:217:7
    at done (/home/travis/build/glayzzle/php-parser/node_modules/mocha/lib/mocha.js:498:13)
    at Runner.<anonymous> (/home/travis/build/glayzzle/php-parser/node_modules/mocha/lib/runner.js:799:5)
    at Runner.emit (events.js:129:20)
    at /home/travis/build/glayzzle/php-parser/node_modules/mocha/lib/runner.js:786:12
    at /home/travis/build/glayzzle/php-parser/node_modules/mocha/lib/runner.js:639:9
    at next (/home/travis/build/glayzzle/php-parser/node_modules/mocha/lib/runner.js:284:14)
    at Immediate._onImmediate (/home/travis/build/glayzzle/php-parser/node_modules/mocha/lib/runner.js:320:5)`
```

**Comment by ichiriac** [comment]
remains a true warning ` Parse Error : syntax error, unexpected ',', expecting 'EXPR' on line 100`, there is some errors in the specified file
