### ISSUE TITLE
Bug with bitwise operators

### ISSUE THREAD

**Issue by rom1504** [glayzzle/php-parser#3]
http://php.net/manual/en/language.operators.bitwise.php

I'm currently using php-parser to parse the PocketMine project and I'm getting an error on this file https://github.com/PocketMine/PocketMine-MP/blob/mcpe-0.12/src/pocketmine/network/protocol/UpdateBlockPacket.php#L36 

```
Error: Parse Error : unexpected '(', expecting 'SCALAR'
    at Object.api.error (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser.js:165:13)
    at Object.read_scalar (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser/scalar.js:88:18)
    at Object.read_constant_declaration (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser/class.js:172:10)
    at Object.api.read_list (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser.js:245:28)
    at Object.read_constant_list (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser/class.js:155:10)
    at Object.read_class_body (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser/class.js:85:38)
    at Object.read_class (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser/class.js:39:34)
    at Object.read_top_statement (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser/statement.js:48:23)
    at Object.read_top_statements (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser/statement.js:17:26)
    at Object.read_namespace (/media/documents/Documents/programmation/interlangage/minecraft/mcpe-protocol-extractor/node_modules/php-parser/src/parser/namespace.js:31:34)
```

It seems the problem is some case of bitwise operators that are not handled.

**Comment by rom1504** [comment]
https://github.com/glayzzle/php-parser/pull/4

**Comment by ichiriac** [comment]
thanks for the fix, checked from zend lexer : 
https://github.com/php/php-src/blob/a49ce7bb91bec02d6f26b3118404371df23242fe/Zend/zend_language_parser.y#L801
