### ISSUE TITLE
Parsing error when silent mode is enabled / new node

### ISSUE THREAD

**Issue by ichiriac** [glayzzle/php-parser#70]
Error :
```
TypeError: Cannot read property 'kind' of undefined
    at parser.read_function_argument_list (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/function.js:188:21)
    at parser.read_new_expr (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/expr.js:466:21)
    at parser.read_expr_item (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/expr.js:212:28)
    at parser.read_expr (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/expr.js:12:21)
    at parser.read_expr_item (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/expr.js:356:26)
    at parser.read_expr (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/expr.js:12:21)
    at parser.read_statement (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/statement.js:343:25)
    at parser.read_inner_statement (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/statement.js:182:21)
    at parser.read_inner_statements (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/statement.js:86:28)
    at parser.read_code_block (/home/devbox/.vscode/extensions/HvyIndustries.crane-0.3.3/server/node_modules/php-parser/src/parser/statement.js:358:14)
```

Raised by :
```php
<?php
        $this->cnx = new \mysqli(
          $this->app->config('data.host'),

        );
```

**Comment by ichiriac** [comment]
Related bug here : https://github.com/HvyIndustries/crane/issues/274 - same error in a call node
