### ISSUE TITLE
Error on `-` in attribute

### ISSUE THREAD

**Issue by Epskampie** [glayzzle/php-parser#899]
Version: 3.1.0-beta.5

The parser errors whenever a `-` (minus) is used inside an attribute.
Sample code:

```php
<?php
namespace App;

class A {
   #[B(-50)]
    public function c()  {  }
}
```
output:

```
[error]     Error: Bad terminal sequence "-" at line 6 (offset 41)
[error]     at Lexer.matchST_ATTRIBUTE (/app/node_modules/php-parser/src/lexer/attribute.js:64:11)
[error]     at Lexer.next (/app/node_modules/php-parser/src/lexer.js:511:26)
[error]     at Lexer.lex (/app/node_modules/php-parser/src/lexer.js:413:20)
[error]     at Parser.lex (/app/node_modules/php-parser/src/parser.js:693:29)
[error]     at Parser.next (/app/node_modules/php-parser/src/parser.js:604:8)
[error]     at Parser.read_argument_list (/app/node_modules/php-parser/src/parser/function.js:341:30)
[error]     at Parser.read_attribute (/app/node_modules/php-parser/src/parser/expr.js:715:19)
[error]     at Parser.read_attr_list (/app/node_modules/php-parser/src/parser/expr.js:725:32)
[error]     at Parser.read_class_body (/app/node_modules/php-parser/src/parser/class.js:93:22)
[error]     at Parser.read_class_declaration_statement (/app/node_modules/php-parser/src/parser/class.js:32:30)
```

**Comment by czosel** [comment]
Fixed in `3.1.0-beta.6` :tada:
